/**
 * Registro de entidades de lançamento de dados.
 *
 * Cada entidade descreve a tabela, os campos com o rótulo usado pelo MEC/INEP e
 * a base legal quando existe. As telas de listagem, criação e edição são geradas
 * a partir daqui — o que garante que todo campo exigido apareça com o mesmo
 * vocabulário do formulário oficial.
 */

export type TipoCampo =
  | "text"
  | "textarea"
  | "number"
  | "decimal"
  | "date"
  | "select"
  | "boolean"
  | "ref"
  | "tags"
  | "senha";

export type Campo = {
  nome: string;
  rotulo: string;
  tipo: TipoCampo;
  opcoes?: string[];
  ref?: string;
  ajuda?: string;
  obrigatorio?: boolean;
  naLista?: boolean;
  largura?: "full" | "half";
  /** Vira filtro na listagem (select para `select`/`boolean`, faixa para `date`). */
  filtravel?: boolean;
};

export type Entidade = {
  slug: string;
  tabela: string;
  rotulo: string;
  rotuloSingular: string;
  grupo: string;
  descricao?: string;
  campoTitulo: string;
  ordenacao?: string;
  campos: Campo[];
  /** Papéis com permissão de escrita; ausente = qualquer papel que não seja de leitura. */
  papeisEscrita?: string[];
  /** Bloqueia a exclusão mesmo para o superadministrador (catálogos regulatórios). */
  permiteExcluir?: boolean;
};

const SIM_NAO = ["true", "false"];

export const ENTIDADES: Entidade[] = [
  // ------------------------------------------------------------ INSTITUCIONAL
  {
    slug: "mantenedora",
    tabela: "mantenedora",
    rotulo: "Mantenedora",
    rotuloSingular: "Mantenedora",
    grupo: "Institucional",
    descricao: "Entidade mantenedora — dados exigidos no Cadastro e-MEC e no Censo, módulo IES.",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Razão social", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "sigla", rotulo: "Sigla", tipo: "text", naLista: true },
      { nome: "cnpj", rotulo: "CNPJ", tipo: "text", naLista: true },
      {
        nome: "natureza",
        rotulo: "Natureza jurídica",
        tipo: "select",
        opcoes: ["PRIVADA_COM_FINS_LUCRATIVOS", "PRIVADA_SEM_FINS_LUCRATIVOS", "PUBLICA", "CONFESSIONAL", "COMUNITARIA"],
      },
      { nome: "representante_legal", rotulo: "Representante legal", tipo: "text" },
      { nome: "endereco", rotulo: "Endereço", tipo: "text", largura: "full" },
      { nome: "municipio", rotulo: "Município", tipo: "text" },
      { nome: "uf", rotulo: "UF", tipo: "text" },
      { nome: "cep", rotulo: "CEP", tipo: "text" },
      { nome: "email", rotulo: "E-mail", tipo: "text" },
      { nome: "telefone", rotulo: "Telefone", tipo: "text" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "ies",
    tabela: "ies",
    rotulo: "Instituição (IES)",
    rotuloSingular: "IES",
    grupo: "Institucional",
    descricao: "Dados cadastrais da mantida, conforme o Cadastro e-MEC (Portaria Normativa MEC nº 21/2017).",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Nome da IES", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "sigla", rotulo: "Sigla", tipo: "text", naLista: true },
      { nome: "codigo_emec", rotulo: "Código e-MEC da IES", tipo: "text", naLista: true },
      { nome: "mantenedora_id", rotulo: "Mantenedora", tipo: "ref", ref: "mantenedora" },
      { nome: "cnpj", rotulo: "CNPJ", tipo: "text" },
      {
        nome: "organizacao_academica",
        rotulo: "Organização acadêmica",
        tipo: "select",
        opcoes: ["FACULDADE", "CENTRO_UNIVERSITARIO", "UNIVERSIDADE", "IFES"],
      },
      {
        nome: "modalidade_credenciamento",
        rotulo: "Modalidade de credenciamento",
        tipo: "select",
        opcoes: ["PRESENCIAL", "EAD", "PRESENCIAL_E_EAD"],
      },
      { nome: "endereco", rotulo: "Endereço da sede", tipo: "text", largura: "full" },
      { nome: "municipio_sede", rotulo: "Município da sede", tipo: "text" },
      { nome: "uf_sede", rotulo: "UF", tipo: "text" },
      { nome: "cep", rotulo: "CEP", tipo: "text" },
      { nome: "codigo_endereco_emec", rotulo: "Código do endereço no e-MEC", tipo: "text" },
      { nome: "procurador_institucional", rotulo: "Procurador Educacional Institucional (PI)", tipo: "text" },
      { nome: "telefone", rotulo: "Telefone", tipo: "text" },
      { nome: "email", rotulo: "E-mail institucional", tipo: "text" },
      { nome: "site", rotulo: "Site", tipo: "text" },
      { nome: "ci", rotulo: "Conceito Institucional (CI)", tipo: "decimal", naLista: true },
      { nome: "ci_ano", rotulo: "Ano do CI", tipo: "number" },
      { nome: "igc", rotulo: "Índice Geral de Cursos (IGC)", tipo: "decimal", naLista: true },
      { nome: "igc_ano", rotulo: "Ano do IGC", tipo: "number" },
      { nome: "fonte", rotulo: "Fonte dos dados", tipo: "text", ajuda: "Ex.: Cadastro e-MEC, consulta em dd/mm/aaaa" },
    ],
  },
  {
    slug: "curso",
    tabela: "curso",
    rotulo: "Cursos",
    rotuloSingular: "Curso",
    grupo: "Institucional",
    descricao:
      "Cursos ofertados. Denominação e eixo tecnológico conforme o CNCST 4ª edição (Portaria MEC nº 514/2024).",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Nome do curso", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "codigo_emec", rotulo: "Código e-MEC do curso", tipo: "text", naLista: true },
      { nome: "ies_id", rotulo: "IES", tipo: "ref", ref: "ies" },
      {
        nome: "grau",
        rotulo: "Grau",
        tipo: "select",
        opcoes: ["TECNOLOGICO", "BACHARELADO", "LICENCIATURA", "SEQUENCIAL"],
        naLista: true,
      },
      {
        nome: "formato_oferta",
        rotulo: "Formato de oferta (Decreto nº 12.456/2025)",
        tipo: "select",
        opcoes: ["PRESENCIAL", "SEMIPRESENCIAL", "A_DISTANCIA"],
        naLista: true,
      },
      { nome: "cncst_denominacao", rotulo: "Denominação no CNCST", tipo: "text" },
      { nome: "cncst_eixo_tecnologico", rotulo: "Eixo tecnológico", tipo: "text" },
      { nome: "carga_horaria_total", rotulo: "Carga horária total (horas)", tipo: "number" },
      {
        nome: "carga_horaria_extensao",
        rotulo: "Carga horária de extensão",
        tipo: "number",
        ajuda: "Mínimo de 10% da carga horária total — Resolução CNE/CES nº 7/2018",
      },
      { nome: "prazo_integralizacao_semestres", rotulo: "Prazo de integralização (semestres)", tipo: "number" },
      { nome: "data_inicio_oferta", rotulo: "Início da oferta", tipo: "date" },
      { nome: "vagas_anuais", rotulo: "Vagas anuais autorizadas", tipo: "number" },
      { nome: "turno", rotulo: "Turno", tipo: "select", opcoes: ["MATUTINO", "VESPERTINO", "NOTURNO", "INTEGRAL", "NAO_APLICAVEL"] },
      { nome: "rotulo_cine_brasil", rotulo: "Rótulo Cine Brasil", tipo: "text", ajuda: "Usado no enquadramento automático do Enade" },
      { nome: "coordenador", rotulo: "Coordenador do curso", tipo: "text" },
      { nome: "cc", rotulo: "Conceito de Curso (CC)", tipo: "decimal", naLista: true },
      { nome: "cc_ano", rotulo: "Ano do CC", tipo: "number" },
      { nome: "cpc", rotulo: "CPC", tipo: "decimal" },
      { nome: "cpc_ano", rotulo: "Ano do CPC", tipo: "number" },
      { nome: "conceito_enade", rotulo: "Conceito Enade", tipo: "decimal" },
      { nome: "enade_area", rotulo: "Área de enquadramento no Enade", tipo: "text" },
      { nome: "enade_sem_area", rotulo: "Sem área correspondente no Enade", tipo: "boolean", opcoes: SIM_NAO },
      {
        nome: "situacao",
        rotulo: "Situação",
        tipo: "select",
        opcoes: ["EM_ATIVIDADE", "EM_EXTINCAO", "EXTINTO", "SUSPENSO"],
      },
      {
        nome: "regime_ead_12456",
        rotulo: "Regime de adequação ao Decreto nº 12.456/2025",
        tipo: "select",
        opcoes: ["TRANSICAO_ATE_19_05_2027", "APLICACAO_IMEDIATA", "NAO_APLICAVEL"],
        ajuda: "Cursos autorizados a partir de 19/05/2025 e pedidos protocolados a partir de 01/08/2025: aplicação imediata.",
      },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "polo",
    tabela: "polo",
    rotulo: "Polos EaD",
    rotuloSingular: "Polo",
    grupo: "Institucional",
    descricao:
      "Polos de educação a distância. Infraestrutura mínima conforme o art. 29 do Decreto nº 12.456/2025 e a Portaria MEC nº 506/2025 (informar no e-MEC em até 60 dias da criação).",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Nome do polo", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "codigo_emec", rotulo: "Código e-MEC do polo", tipo: "text", naLista: true },
      { nome: "ies_id", rotulo: "IES", tipo: "ref", ref: "ies" },
      { nome: "endereco", rotulo: "Endereço", tipo: "text", largura: "full" },
      { nome: "municipio", rotulo: "Município", tipo: "text", naLista: true },
      { nome: "uf", rotulo: "UF", tipo: "text" },
      { nome: "cep", rotulo: "CEP", tipo: "text" },
      { nome: "situacao", rotulo: "Situação", tipo: "select", opcoes: ["ATIVO", "EM_IMPLANTACAO", "SUSPENSO", "EXTINTO"], naLista: true },
      { nome: "data_criacao", rotulo: "Data de criação", tipo: "date" },
      { nome: "data_informe_emec", rotulo: "Data do informe no e-MEC", tipo: "date", ajuda: "Prazo de 60 dias — Portaria MEC nº 506/2025" },
      { nome: "responsavel", rotulo: "Responsável pelo polo", tipo: "text" },
      { nome: "vagas_totais", rotulo: "Vagas totais do polo", tipo: "number" },
      { nome: "area_m2", rotulo: "Área total (m²)", tipo: "decimal" },
      { nome: "laboratorios", rotulo: "Laboratórios e ambientes de prática", tipo: "textarea", largura: "full" },
      { nome: "biblioteca", rotulo: "Biblioteca / acervo disponível", tipo: "textarea", largura: "full" },
      { nome: "acessibilidade", rotulo: "Condições de acessibilidade", tipo: "textarea", largura: "full" },
      { nome: "infraestrutura_tecnologica", rotulo: "Infraestrutura tecnológica", tipo: "textarea", largura: "full" },
      {
        nome: "adequacao_12456_status",
        rotulo: "Status de adequação ao Decreto nº 12.456/2025",
        tipo: "select",
        opcoes: ["NAO_INICIADA", "EM_ADEQUACAO", "ADEQUADO"],
        naLista: true,
      },
      { nome: "adequacao_12456_prazo", rotulo: "Prazo de adequação", tipo: "date" },
      { nome: "adequacao_12456_plano", rotulo: "Plano de adequação", tipo: "textarea", largura: "full" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "ato",
    tabela: "ato_regulatorio",
    rotulo: "Atos autorizativos",
    rotuloSingular: "Ato autorizativo",
    grupo: "Institucional",
    descricao:
      "Credenciamento, recredenciamento, autorização, reconhecimento e renovação. Protocolo tempestivo prorroga a validade do ato.",
    campoTitulo: "tipo",
    ordenacao: "data_publicacao desc nulls last",
    campos: [
      {
        nome: "tipo",
        rotulo: "Tipo de ato",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: [
          "CREDENCIAMENTO",
          "RECREDENCIAMENTO",
          "CREDENCIAMENTO_EAD",
          "AUTORIZACAO",
          "RECONHECIMENTO",
          "RENOVACAO_RECONHECIMENTO",
          "ADITAMENTO",
        ],
      },
      { nome: "escopo", rotulo: "Escopo", tipo: "select", opcoes: ["IES", "CURSO", "POLO"], naLista: true },
      { nome: "ies_id", rotulo: "IES", tipo: "ref", ref: "ies" },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "especie_ato", rotulo: "Espécie do ato", tipo: "select", opcoes: ["Portaria", "Despacho", "Resolução"] },
      { nome: "numero_ato", rotulo: "Número do ato", tipo: "text", naLista: true },
      { nome: "data_assinatura", rotulo: "Data de assinatura", tipo: "date" },
      { nome: "data_publicacao", rotulo: "Data de publicação no DOU", tipo: "date", naLista: true },
      { nome: "secao_dou", rotulo: "Seção do DOU", tipo: "text" },
      { nome: "pagina_dou", rotulo: "Página do DOU", tipo: "text" },
      { nome: "vigencia_inicio", rotulo: "Início da vigência", tipo: "date" },
      { nome: "vigencia_fim", rotulo: "Fim da vigência", tipo: "date", naLista: true },
      { nome: "prorrogado", rotulo: "Prorrogado por protocolo tempestivo", tipo: "boolean" },
      { nome: "processo_emec", rotulo: "Processo e-MEC", tipo: "text" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },

  // -------------------------------------------------------------- REGULATÓRIO
  {
    slug: "processo",
    tabela: "processo_regulatorio",
    rotulo: "Processos e-MEC",
    rotuloSingular: "Processo",
    grupo: "Regulatório",
    descricao: "Fluxo dos processos regulatórios conforme a Portaria Normativa MEC nº 23/2017.",
    campoTitulo: "numero_processo",
    ordenacao: "criado_em desc",
    campos: [
      { nome: "numero_processo", rotulo: "Número do processo e-MEC", tipo: "text", naLista: true },
      { nome: "codigo_avaliacao", rotulo: "Código da avaliação", tipo: "text", naLista: true },
      {
        nome: "tipo",
        rotulo: "Tipo",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: [
          "CREDENCIAMENTO",
          "RECREDENCIAMENTO",
          "CREDENCIAMENTO_EAD",
          "AUTORIZACAO",
          "RECONHECIMENTO",
          "RENOVACAO_RECONHECIMENTO",
          "ADITAMENTO_POLO",
          "ADITAMENTO_VAGAS",
        ],
      },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "ies_id", rotulo: "IES", tipo: "ref", ref: "ies" },
      {
        nome: "fase",
        rotulo: "Fase atual",
        tipo: "select",
        naLista: true,
        opcoes: [
          "PLANEJAMENTO",
          "PROTOCOLO",
          "DESPACHO_SANEADOR",
          "ANALISE_DOCUMENTAL",
          "AVALIACAO_IN_LOCO",
          "IMPUGNACAO_CTAA",
          "PARECER_SERES",
          "DECISAO",
          "PUBLICACAO_DOU",
          "ARQUIVADO",
        ],
      },
      { nome: "data_protocolo", rotulo: "Data do protocolo", tipo: "date" },
      {
        nome: "janela_inicio",
        rotulo: "Início da janela de protocolo",
        tipo: "date",
        ajuda: "Reconhecimento: entre 50% e 75% da carga horária integralizada",
      },
      { nome: "janela_fim", rotulo: "Fim da janela de protocolo", tipo: "date", naLista: true },
      { nome: "prazo_parecer", rotulo: "Prazo estimado do parecer", tipo: "date" },
      { nome: "taxa_paga", rotulo: "Taxa de avaliação paga", tipo: "boolean", ajuda: "O não pagamento cancela o processo" },
      { nome: "taxa_vencimento", rotulo: "Vencimento da taxa", tipo: "date" },
      { nome: "prazos_suspensos", rotulo: "Prazos suspensos (supervisão/diligência)", tipo: "boolean" },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "visita",
    tabela: "visita_in_loco",
    rotulo: "Visitas in loco",
    rotuloSingular: "Visita in loco",
    grupo: "Regulatório",
    descricao: "Avaliação externa, presencial ou virtual (Portaria MEC nº 265/2022).",
    campoTitulo: "codigo_avaliacao",
    ordenacao: "data_inicio desc nulls last",
    campos: [
      { nome: "codigo_avaliacao", rotulo: "Código da avaliação", tipo: "text", naLista: true },
      { nome: "processo_id", rotulo: "Processo", tipo: "ref", ref: "processo" },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "modalidade", rotulo: "Modalidade", tipo: "select", opcoes: ["PRESENCIAL", "VIRTUAL"], naLista: true },
      { nome: "data_inicio", rotulo: "Data de início", tipo: "date", naLista: true },
      { nome: "data_fim", rotulo: "Data de término", tipo: "date" },
      { nome: "comissao", rotulo: "Comissão avaliadora", tipo: "textarea", largura: "full" },
      { nome: "ponto_focal", rotulo: "Ponto focal da comissão", tipo: "text" },
      { nome: "link_nuvem", rotulo: "Link da nuvem com o pacote de evidências", tipo: "text", largura: "full" },
      { nome: "status", rotulo: "Status", tipo: "select", opcoes: ["PLANEJADA", "AGENDADA", "REALIZADA", "CANCELADA"], naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "prazo",
    tabela: "prazo",
    rotulo: "Prazos e obrigações",
    rotuloSingular: "Prazo",
    grupo: "Regulatório",
    descricao: "Calendário unificado das obrigações regulatórias, censitárias e avaliativas.",
    campoTitulo: "titulo",
    ordenacao: "data_limite asc",
    campos: [
      { nome: "titulo", rotulo: "Obrigação", tipo: "text", obrigatorio: true, naLista: true },
      {
        nome: "categoria",
        rotulo: "Categoria",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["REGULATORIO", "ENADE", "CENSO", "CPA", "EAD", "SUPERVISAO", "INTERNO"],
      },
      { nome: "data_limite", rotulo: "Data limite", tipo: "date", obrigatorio: true, naLista: true },
      { nome: "data_inicio", rotulo: "Início do período", tipo: "date" },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso" },
      { nome: "base_legal", rotulo: "Base legal", tipo: "text", largura: "full" },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text" },
      { nome: "criticidade", rotulo: "Criticidade", tipo: "select", opcoes: ["CRITICA", "ALTA", "MEDIA", "BAIXA"], naLista: true },
      { nome: "status", rotulo: "Status", tipo: "select", opcoes: ["PENDENTE", "EM_ANDAMENTO", "CONCLUIDO", "SUSPENSO"], naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "supervisao",
    tabela: "supervisao_ocorrencia",
    rotulo: "Supervisão",
    rotuloSingular: "Ocorrência de supervisão",
    grupo: "Regulatório",
    descricao:
      "Diligências, protocolo de compromisso e medidas cautelares. Enquanto ativas, suspendem a contagem dos prazos regulatórios.",
    campoTitulo: "numero",
    ordenacao: "criado_em desc",
    campos: [
      {
        nome: "tipo",
        rotulo: "Tipo",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["DILIGENCIA", "PROTOCOLO_DE_COMPROMISSO", "MEDIDA_CAUTELAR", "PROCESSO_ADMINISTRATIVO", "MONITORAMENTO"],
      },
      {
        nome: "origem",
        rotulo: "Origem",
        tipo: "select",
        opcoes: ["DENUNCIA", "OFICIO", "RESULTADO_INSATISFATORIO", "CPC_OU_CI_ABAIXO_DE_3", "OUTRA"],
      },
      { nome: "numero", rotulo: "Número/identificação", tipo: "text", naLista: true },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "data_ciencia", rotulo: "Data de ciência", tipo: "date", naLista: true },
      { nome: "prazo_resposta", rotulo: "Prazo de resposta", tipo: "date", naLista: true },
      { nome: "situacao", rotulo: "Situação", tipo: "select", opcoes: ["ABERTA", "EM_RESPOSTA", "RESPONDIDA", "ENCERRADA"], naLista: true },
      { nome: "suspende_prazos", rotulo: "Suspende prazos regulatórios", tipo: "boolean" },
      { nome: "medidas", rotulo: "Medidas determinadas", tipo: "textarea", largura: "full" },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text" },
      { nome: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "full" },
    ],
  },

  // ---------------------------------------------------------------------- CPA
  {
    slug: "cpa-ciclo",
    tabela: "cpa_ciclo",
    rotulo: "Ciclos da CPA",
    rotuloSingular: "Ciclo da CPA",
    grupo: "CPA",
    descricao: "Ciclo anual de autoavaliação institucional (Lei nº 10.861/2004).",
    campoTitulo: "titulo",
    ordenacao: "ano_referencia desc",
    campos: [
      { nome: "titulo", rotulo: "Título do ciclo", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "ano_referencia", rotulo: "Ano de referência", tipo: "number", obrigatorio: true, naLista: true },
      { nome: "tipo_relatorio", rotulo: "Tipo de relatório", tipo: "select", opcoes: ["PARCIAL", "INTEGRAL"], naLista: true },
      {
        nome: "etapa",
        rotulo: "Etapa",
        tipo: "select",
        naLista: true,
        opcoes: ["SENSIBILIZACAO", "COLETA", "ANALISE", "RELATORIO", "DEVOLUTIVA"],
      },
      { nome: "inicio_coleta", rotulo: "Início da coleta", tipo: "date" },
      { nome: "fim_coleta", rotulo: "Fim da coleta", tipo: "date" },
      { nome: "data_postagem_emec", rotulo: "Postagem do relatório no e-MEC", tipo: "date", ajuda: "Prazo usual: 31 de março" },
      { nome: "participacao_discentes", rotulo: "Participação de discentes (%)", tipo: "decimal" },
      { nome: "participacao_docentes", rotulo: "Participação de docentes (%)", tipo: "decimal" },
      { nome: "participacao_tecnicos", rotulo: "Participação de técnico-administrativos (%)", tipo: "decimal" },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text" },
      { nome: "status", rotulo: "Status", tipo: "select", opcoes: ["ABERTO", "ENCERRADO"], naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "cpa-resultado",
    tabela: "cpa_resultado",
    rotulo: "Resultados da CPA",
    rotuloSingular: "Resultado da CPA",
    grupo: "CPA",
    descricao: "Resultados por segmento e por eixo/dimensão do SINAES, com a ação de melhoria decorrente.",
    campoTitulo: "pergunta",
    campos: [
      { nome: "cpa_ciclo_id", rotulo: "Ciclo", tipo: "ref", ref: "cpa-ciclo", obrigatorio: true, naLista: true },
      {
        nome: "segmento",
        rotulo: "Segmento",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["DISCENTE", "DOCENTE", "TUTOR", "TECNICO_ADMINISTRATIVO", "EGRESSO", "COMUNIDADE_EXTERNA"],
      },
      { nome: "eixo_numero", rotulo: "Eixo do instrumento (1 a 5)", tipo: "number", naLista: true },
      { nome: "dimensao_sinaes", rotulo: "Dimensão do SINAES (1 a 10)", tipo: "number" },
      { nome: "pergunta", rotulo: "Pergunta / aspecto avaliado", tipo: "textarea", largura: "full", naLista: true },
      { nome: "media", rotulo: "Média obtida", tipo: "decimal", naLista: true },
      { nome: "respondentes", rotulo: "Respondentes", tipo: "number" },
      { nome: "acao_melhoria", rotulo: "Ação de melhoria decorrente", tipo: "textarea", largura: "full" },
    ],
  },

  // -------------------------------------------------------- COLEGIADOS/PESSOAS
  {
    slug: "colegiado",
    tabela: "colegiado",
    rotulo: "Colegiados",
    rotuloSingular: "Colegiado",
    grupo: "Colegiados",
    descricao:
      "NDE, equipe multidisciplinar, colegiado de curso, CPA e conselhos. NDE: mínimo de 5 docentes, 60% com stricto sensu e 20% em tempo integral.",
    campoTitulo: "nome",
    campos: [
      {
        nome: "tipo",
        rotulo: "Tipo",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["NDE", "EQUIPE_MULTIDISCIPLINAR", "COLEGIADO_CURSO", "CPA", "CONSUP", "CONSEPE", "OUTRO"],
      },
      { nome: "nome", rotulo: "Nome", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "ato_designacao", rotulo: "Ato de designação", tipo: "text" },
      { nome: "data_designacao", rotulo: "Data da designação", tipo: "date" },
      { nome: "mandato_meses", rotulo: "Mandato (meses)", tipo: "number" },
      { nome: "regimento", rotulo: "Regimento / normativo interno", tipo: "textarea", largura: "full" },
      { nome: "atribuicoes", rotulo: "Atribuições", tipo: "textarea", largura: "full" },
      { nome: "situacao", rotulo: "Situação", tipo: "select", opcoes: ["ATIVO", "INATIVO"], naLista: true },
    ],
  },
  {
    slug: "membro",
    tabela: "colegiado_membro",
    rotulo: "Membros de colegiado",
    rotuloSingular: "Membro",
    grupo: "Colegiados",
    descricao: "Composição e histórico. A permanência dos membros é avaliada pelo indicador 2.1 do instrumento de curso.",
    campoTitulo: "nome",
    campos: [
      { nome: "colegiado_id", rotulo: "Colegiado", tipo: "ref", ref: "colegiado", obrigatorio: true, naLista: true },
      { nome: "nome", rotulo: "Nome", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "pessoa_id", rotulo: "Pessoa cadastrada", tipo: "ref", ref: "pessoa" },
      {
        nome: "perfil",
        rotulo: "Perfil",
        tipo: "select",
        naLista: true,
        opcoes: [
          "DOCENTE",
          "TUTOR",
          "DESIGNER_INSTRUCIONAL",
          "REVISOR",
          "PRODUTOR_DE_MIDIA",
          "TECNOLOGIA_DA_INFORMACAO",
          "DISCENTE",
          "TECNICO_ADMINISTRATIVO",
          "COMUNIDADE_EXTERNA",
        ],
      },
      { nome: "titulacao", rotulo: "Titulação", tipo: "select", opcoes: ["GRADUACAO", "ESPECIALIZACAO", "MESTRADO", "DOUTORADO"], naLista: true },
      { nome: "regime_trabalho", rotulo: "Regime de trabalho", tipo: "select", opcoes: ["HORISTA", "PARCIAL", "INTEGRAL"], naLista: true },
      { nome: "funcao", rotulo: "Função no colegiado", tipo: "text" },
      { nome: "desde", rotulo: "Membro desde", tipo: "date" },
      { nome: "ate", rotulo: "Membro até", tipo: "date" },
    ],
  },
  {
    slug: "reuniao",
    tabela: "reuniao",
    rotulo: "Reuniões e atas",
    rotuloSingular: "Reunião",
    grupo: "Colegiados",
    descricao: "Registro de reuniões, pautas e deliberações — evidência recorrente nos indicadores 1.13, 2.1 e 2.12.",
    campoTitulo: "pauta",
    ordenacao: "data desc",
    campos: [
      { nome: "colegiado_id", rotulo: "Colegiado", tipo: "ref", ref: "colegiado", obrigatorio: true, naLista: true },
      { nome: "data", rotulo: "Data", tipo: "date", obrigatorio: true, naLista: true },
      { nome: "pauta", rotulo: "Pauta", tipo: "textarea", largura: "full", naLista: true },
      { nome: "deliberacoes", rotulo: "Deliberações", tipo: "textarea", largura: "full" },
      { nome: "participantes", rotulo: "Participantes", tipo: "textarea", largura: "full" },
      { nome: "documento_id", rotulo: "Ata (documento)", tipo: "ref", ref: "documento" },
    ],
  },
  {
    slug: "pessoa",
    tabela: "pessoa",
    rotulo: "Corpo docente e tutorial",
    rotuloSingular: "Pessoa",
    grupo: "Colegiados",
    descricao:
      "Docentes, tutores, mediadores pedagógicos e responsáveis de polo (Portaria MEC nº 506/2025). Base de cálculo dos indicadores 2.5 a 2.16 e do módulo Docente do Censo.",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Nome", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "email", rotulo: "E-mail", tipo: "text" },
      {
        nome: "funcao",
        rotulo: "Função",
        tipo: "select",
        naLista: true,
        opcoes: ["DOCENTE", "TUTOR", "MEDIADOR_PEDAGOGICO", "COORDENADOR", "RESPONSAVEL_POLO", "TECNICO_ADMINISTRATIVO"],
      },
      { nome: "titulacao", rotulo: "Titulação", tipo: "select", opcoes: ["GRADUACAO", "ESPECIALIZACAO", "MESTRADO", "DOUTORADO"], naLista: true },
      { nome: "area_titulacao", rotulo: "Área da titulação", tipo: "text" },
      { nome: "regime_trabalho", rotulo: "Regime de trabalho", tipo: "select", opcoes: ["HORISTA", "PARCIAL", "INTEGRAL"], naLista: true },
      { nome: "curso_id", rotulo: "Curso de atuação", tipo: "ref", ref: "curso", naLista: true },
      { nome: "polo_id", rotulo: "Polo de atuação", tipo: "ref", ref: "polo" },
      { nome: "data_admissao", rotulo: "Data de admissão", tipo: "date" },
      { nome: "meses_docencia_superior", rotulo: "Docência superior (meses)", tipo: "number" },
      { nome: "meses_docencia_ead", rotulo: "Docência em EaD (meses)", tipo: "number" },
      { nome: "meses_tutoria_ead", rotulo: "Tutoria em EaD (meses)", tipo: "number" },
      { nome: "meses_experiencia_profissional", rotulo: "Experiência profissional fora da docência (meses)", tipo: "number" },
      { nome: "producao_ultimos_3_anos", rotulo: "Produções nos últimos 3 anos", tipo: "number" },
      { nome: "lattes", rotulo: "Currículo Lattes", tipo: "text", largura: "full" },
      { nome: "disciplinas", rotulo: "Disciplinas atribuídas", tipo: "textarea", largura: "full" },
      { nome: "situacao", rotulo: "Situação", tipo: "select", opcoes: ["ATIVO", "AFASTADO", "DESLIGADO"], naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },

  // -------------------------------------------------------------------- ENADE
  {
    slug: "enade-ciclo",
    tabela: "enade_ciclo",
    rotulo: "Edições do ENADE",
    rotuloSingular: "Edição do ENADE",
    grupo: "ENADE",
    descricao: "Edições, modalidades e cronograma (Portaria Normativa Inep nº 359/2025 e edital do ano).",
    campoTitulo: "ano",
    ordenacao: "ano desc",
    campos: [
      { nome: "ano", rotulo: "Ano da edição", tipo: "number", obrigatorio: true, naLista: true },
      { nome: "ano_ciclo", rotulo: "Ano do ciclo avaliativo (1 a 3)", tipo: "number" },
      { nome: "modalidades", rotulo: "Modalidades", tipo: "textarea", largura: "full" },
      { nome: "areas", rotulo: "Áreas avaliadas", tipo: "textarea", largura: "full", naLista: true },
      { nome: "edital", rotulo: "Edital", tipo: "text" },
      { nome: "data_prova", rotulo: "Data da prova", tipo: "date", naLista: true },
      { nome: "inscricao_inicio", rotulo: "Início das inscrições", tipo: "date" },
      { nome: "inscricao_fim", rotulo: "Fim das inscrições", tipo: "date", naLista: true },
      { nome: "questionario_inicio", rotulo: "Início do Questionário do Estudante", tipo: "date" },
      { nome: "questionario_fim", rotulo: "Fim do Questionário do Estudante", tipo: "date" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "enade-curso",
    tabela: "curso_enade_edicao",
    rotulo: "Enquadramento por curso",
    rotuloSingular: "Enquadramento",
    grupo: "ENADE",
    descricao:
      "Situação de cada curso na edição. Curso sem área correspondente exige declaração no Sistema Enade dentro do prazo.",
    campoTitulo: "area_avaliacao",
    campos: [
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", obrigatorio: true, naLista: true },
      { nome: "enade_ciclo_id", rotulo: "Edição", tipo: "ref", ref: "enade-ciclo", obrigatorio: true, naLista: true },
      { nome: "enquadrado", rotulo: "Curso enquadrado", tipo: "boolean", naLista: true },
      { nome: "area_avaliacao", rotulo: "Área de avaliação", tipo: "text" },
      { nome: "motivo_nao_enquadramento", rotulo: "Motivo do não enquadramento", tipo: "textarea", largura: "full" },
      { nome: "declaracao_nao_enquadramento", rotulo: "Declaração registrada no Sistema Enade", tipo: "boolean", naLista: true },
      { nome: "proximo_ciclo_previsto", rotulo: "Próxima edição prevista", tipo: "number" },
      { nome: "concluintes_previstos", rotulo: "Concluintes previstos", tipo: "number" },
      { nome: "inscritos", rotulo: "Inscritos", tipo: "number", naLista: true },
      { nome: "regulares", rotulo: "Regulares", tipo: "number" },
      { nome: "irregulares", rotulo: "Irregulares", tipo: "number", naLista: true },
      { nome: "conceito_obtido", rotulo: "Conceito Enade obtido", tipo: "decimal" },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "enade-estudante",
    tabela: "enade_estudante",
    rotulo: "Estudantes do ENADE",
    rotuloSingular: "Estudante",
    grupo: "ENADE",
    descricao:
      "Habilitação: concluinte de CST a partir de 75% da carga horária; ingressante entre 0 e 25%. Situação irregular impede a colação de grau e a emissão do diploma.",
    campoTitulo: "nome",
    campos: [
      { nome: "curso_enade_edicao_id", rotulo: "Enquadramento (curso/edição)", tipo: "ref", ref: "enade-curso", obrigatorio: true },
      { nome: "ra", rotulo: "RA / matrícula", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "nome", rotulo: "Nome", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "habilitacao", rotulo: "Habilitação", tipo: "select", opcoes: ["INGRESSANTE", "CONCLUINTE"], naLista: true },
      { nome: "percentual_integralizacao", rotulo: "Percentual de integralização", tipo: "decimal", naLista: true },
      { nome: "ano_fim_ensino_medio", rotulo: "Ano de conclusão do ensino médio", tipo: "number" },
      { nome: "ano_formatura", rotulo: "Ano previsto de formatura", tipo: "number" },
      {
        nome: "situacao",
        rotulo: "Situação",
        tipo: "select",
        naLista: true,
        opcoes: [
          "PENDENTE_INSCRICAO",
          "INSCRITO",
          "DISPENSADO",
          "PRESENTE",
          "AUSENTE",
          "REGULAR",
          "IRREGULAR",
        ],
      },
      { nome: "questionario_respondido", rotulo: "Questionário do Estudante respondido", tipo: "boolean", naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },

  // -------------------------------------------------------------------- CENSO
  {
    slug: "censo-ano",
    tabela: "censo_ano",
    rotulo: "Ciclos do Censo",
    rotuloSingular: "Ciclo do Censo",
    grupo: "CENSO",
    descricao: "Censo da Educação Superior — Censup. A IES que não fecha os módulos é inativada, com publicação no DOU.",
    campoTitulo: "ano_referencia",
    ordenacao: "ano_referencia desc",
    campos: [
      { nome: "ano_referencia", rotulo: "Ano de referência", tipo: "number", obrigatorio: true, naLista: true },
      { nome: "portaria", rotulo: "Portaria do cronograma", tipo: "text", naLista: true },
      { nome: "coleta_inicio", rotulo: "Início da coleta", tipo: "date", naLista: true },
      { nome: "coleta_fim", rotulo: "Fim da coleta", tipo: "date", naLista: true },
      { nome: "conclusao_insercao", rotulo: "Conclusão da inserção de dados", tipo: "date" },
      { nome: "justificativas_fim", rotulo: "Prazo final de justificativas", tipo: "date" },
      { nome: "divulgacao_prevista", rotulo: "Divulgação dos resultados", tipo: "date" },
      { nome: "recenseador", rotulo: "Recenseador institucional", tipo: "text" },
      { nome: "status", rotulo: "Status", tipo: "select", opcoes: ["PLANEJADO", "EM_COLETA", "ENCERRAMENTO", "FECHADO"], naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "censo-modulo",
    tabela: "censo_modulo",
    rotulo: "Módulos do Censo",
    rotuloSingular: "Módulo do Censo",
    grupo: "CENSO",
    descricao: "Fluxo por módulo: declarar → verificar erros → relatório de consistência → justificar → fechar.",
    campoTitulo: "modulo",
    campos: [
      { nome: "censo_ano_id", rotulo: "Ciclo", tipo: "ref", ref: "censo-ano", obrigatorio: true, naLista: true },
      { nome: "modulo", rotulo: "Módulo", tipo: "select", obrigatorio: true, naLista: true, opcoes: ["IES", "CURSO", "DOCENTE", "ALUNO"] },
      {
        nome: "status",
        rotulo: "Status",
        tipo: "select",
        naLista: true,
        opcoes: ["NAO_INICIADO", "EM_PREENCHIMENTO", "EM_VERIFICACAO", "COM_PENDENCIAS", "PRONTO_PARA_FECHAR", "FECHADO"],
      },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text", naLista: true },
      { nome: "registros_declarados", rotulo: "Registros declarados", tipo: "number", naLista: true },
      { nome: "observacao", rotulo: "Observações", tipo: "textarea", largura: "full" },
    ],
  },
  {
    slug: "censo-pendencia",
    tabela: "censo_pendencia",
    rotulo: "Pendências do Censo",
    rotuloSingular: "Pendência",
    grupo: "CENSO",
    descricao: "Erros e inconsistências apontados pelo Censup, com justificativa e responsável.",
    campoTitulo: "descricao",
    campos: [
      { nome: "censo_modulo_id", rotulo: "Módulo", tipo: "ref", ref: "censo-modulo", obrigatorio: true, naLista: true },
      { nome: "tipo", rotulo: "Tipo", tipo: "select", opcoes: ["ERRO", "INCONSISTENCIA", "ALERTA"], naLista: true },
      { nome: "codigo", rotulo: "Código da crítica", tipo: "text", naLista: true },
      { nome: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "full", naLista: true },
      { nome: "registro_ref", rotulo: "Registro afetado", tipo: "text" },
      { nome: "justificativa", rotulo: "Justificativa enviada", tipo: "textarea", largura: "full" },
      { nome: "responsavel", rotulo: "Responsável", tipo: "text" },
      { nome: "status", rotulo: "Status", tipo: "select", opcoes: ["ABERTA", "JUSTIFICADA", "CORRIGIDA", "ACEITA"], naLista: true },
    ],
  },

  // --------------------------------------------------------------- DOCUMENTOS
  {
    slug: "documento",
    tabela: "documento",
    rotulo: "Documentos",
    rotuloSingular: "Documento",
    grupo: "Documentos",
    descricao:
      "Acervo de evidências com versionamento e hash SHA-256 (Portaria MEC nº 315/2018). Evidência vencida reabre a lacuna do indicador.",
    campoTitulo: "titulo",
    ordenacao: "criado_em desc",
    campos: [
      { nome: "titulo", rotulo: "Título", tipo: "text", obrigatorio: true, naLista: true },
      {
        nome: "categoria",
        rotulo: "Categoria",
        tipo: "select",
        naLista: true,
        opcoes: [
          "PDI",
          "PPC",
          "REGIMENTO",
          "ATA",
          "RELATORIO_CPA",
          "POLITICA_INSTITUCIONAL",
          "CONTRATO",
          "LAUDO",
          "PLANILHA",
          "ATO_REGULATORIO",
          "MATERIAL_DIDATICO",
          "REGISTRO_FOTOGRAFICO",
          "OUTRO",
        ],
      },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "polo_id", rotulo: "Polo", tipo: "ref", ref: "polo" },
      { nome: "versao", rotulo: "Versão", tipo: "number", naLista: true },
      { nome: "valido_de", rotulo: "Válido de", tipo: "date" },
      { nome: "valido_ate", rotulo: "Válido até", tipo: "date", naLista: true },
      {
        nome: "status",
        rotulo: "Status",
        tipo: "select",
        naLista: true,
        opcoes: ["RASCUNHO", "EM_APROVACAO", "VIGENTE", "SUPERADO"],
      },
      { nome: "aprovado_por", rotulo: "Aprovado por", tipo: "text" },
      { nome: "descricao", rotulo: "Descrição", tipo: "textarea", largura: "full" },
    ],
  },

  // ----------------------------------------------------------------- LEGALONE
  {
    slug: "norma",
    tabela: "norma",
    rotulo: "Base normativa",
    rotuloSingular: "Norma",
    grupo: "LegalOne",
    descricao: "Normas do MEC, INEP, CNE e legislação correlata, com impacto nos indicadores.",
    campoTitulo: "ementa",
    ordenacao: "data_publicacao desc nulls last",
    campos: [
      {
        nome: "especie",
        rotulo: "Espécie",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["LEI", "DECRETO", "PORTARIA", "PORTARIA_NORMATIVA", "RESOLUCAO", "PARECER", "EDITAL", "NOTA_TECNICA", "INSTRUCAO_NORMATIVA"],
      },
      { nome: "orgao", rotulo: "Órgão", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "numero", rotulo: "Número", tipo: "text", naLista: true },
      { nome: "ano", rotulo: "Ano", tipo: "number", naLista: true },
      { nome: "data_assinatura", rotulo: "Data de assinatura", tipo: "date" },
      { nome: "data_publicacao", rotulo: "Data de publicação no DOU", tipo: "date", naLista: true },
      { nome: "ementa", rotulo: "Ementa", tipo: "textarea", obrigatorio: true, largura: "full", naLista: true },
      { nome: "url_dou", rotulo: "URL do DOU / fonte oficial", tipo: "text", largura: "full" },
      { nome: "vigente", rotulo: "Vigente", tipo: "boolean", naLista: true },
      { nome: "relevancia", rotulo: "Relevância", tipo: "select", opcoes: ["CRITICA", "ALTA", "MEDIA", "BAIXA"], naLista: true },
      { nome: "tags", rotulo: "Tags", tipo: "tags", ajuda: "Separe por vírgula" },
      { nome: "observacao", rotulo: "Impacto institucional", tipo: "textarea", largura: "full" },
    ],
  },

  // --------------------------------------------------------------- QUALIDADE
  {
    slug: "indicador-qualidade",
    tabela: "indicador_qualidade",
    rotulo: "Indicadores de qualidade",
    rotuloSingular: "Indicador de qualidade",
    grupo: "Administração",
    descricao: "Série histórica de CI, CC, CPC, IDD, IGC e Conceito Enade.",
    campoTitulo: "tipo",
    ordenacao: "ano desc",
    campos: [
      { nome: "tipo", rotulo: "Indicador", tipo: "select", obrigatorio: true, naLista: true, opcoes: ["CI", "CC", "CPC", "IDD", "IGC", "ENADE"] },
      { nome: "escopo", rotulo: "Escopo", tipo: "select", opcoes: ["IES", "CURSO"], naLista: true },
      { nome: "ies_id", rotulo: "IES", tipo: "ref", ref: "ies" },
      { nome: "curso_id", rotulo: "Curso", tipo: "ref", ref: "curso", naLista: true },
      { nome: "ano", rotulo: "Ano", tipo: "number", obrigatorio: true, naLista: true },
      { nome: "valor", rotulo: "Valor contínuo", tipo: "decimal", naLista: true },
      { nome: "faixa", rotulo: "Faixa (1 a 5)", tipo: "number", naLista: true },
      { nome: "fonte", rotulo: "Fonte", tipo: "text" },
    ],
  },
  {
    slug: "usuario",
    tabela: "usuario",
    rotulo: "Usuários",
    rotuloSingular: "Usuário",
    grupo: "Administração",
    descricao: "Acesso ao sistema por papel. Papéis AUDITOR e DOCENTE têm acesso somente de leitura.",
    campoTitulo: "nome",
    campos: [
      { nome: "nome", rotulo: "Nome", tipo: "text", obrigatorio: true, naLista: true },
      { nome: "email", rotulo: "E-mail", tipo: "text", obrigatorio: true, naLista: true },
      {
        nome: "papel",
        rotulo: "Papel",
        tipo: "select",
        obrigatorio: true,
        naLista: true,
        opcoes: ["SUPERADMIN", "DIRETOR", "PI", "RESPONSAVEL_LEGAL", "COORD_CURSO", "CPA", "NDE", "SECRETARIA", "DOCENTE", "AUDITOR"],
      },
      { nome: "ativo", rotulo: "Ativo", tipo: "boolean", naLista: true },
      {
        nome: "senha",
        rotulo: "Senha de acesso",
        tipo: "senha",
        largura: "full",
        ajuda:
          "Defina a senha e informe-a ao usuário: o sistema não envia e-mail de convite. Ao editar, deixe em branco para manter a senha atual.",
      },
    ],
  },
];

export const GRUPOS = [
  "Institucional",
  "Regulatório",
  "CPA",
  "Colegiados",
  "ENADE",
  "CENSO",
  "LegalOne",
  "Administração",
] as const;

export function entidadePorSlug(slug: string): Entidade | undefined {
  return ENTIDADES.find((e) => e.slug === slug);
}

export function entidadesDoGrupo(grupo: string): Entidade[] {
  return ENTIDADES.filter((e) => e.grupo === grupo);
}
